import "./globals.css";
import type { Metadata } from "next";
import { Syne } from "next/font/google"

const syne = Syne({
  subsets: ["latin"],
  display: "block",
  weight: ["400","500","600","700","800"]
})


export const metadata: Metadata = {
  title: "JahezAbrahamJohny",
  description: "Generated by create next app",
  //colorScheme: "dark",
  category: "technology"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${syne.className} scroll-smooth antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
